# 1
# 2
# 3
spring:
  application:
    name: argo-admin
  ai:
    openai:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7