# 1
# 2
# 3
spring:
  application:
    name: argo-admin
  ai:
    openai:
      chat:
        options:
          model: hunyuan-functioncall
          temperature: 0.7
      base-url: https://api.hunyuan.cloud.tencent.com